### ISSUE TITLE
Update to MWA (SMART) survey candidate website

### ISSUE THREAD

**Issue by bwmeyers** [dlakaplan/pulsarsurveyscraper#10]
The website to scrape for MWA pulsar candidates is now: 

`https://mwatelescope.atlassian.net/wiki/spaces/MP/pages/24970773/SMART+survey+candidates` 

The formatting should be identical, and it is publicly accessible. (The old MWA wiki was deprecated and will not be updated.)

**Comment by dlakaplan** [comment]
Thanks - that has been updated.
